### ISSUE TITLE
Graph for Boba U4 62g?

### ISSUE THREAD

**Issue by qazip** [bluepylons/Open-Switch-Curve-Meter#1]
You seem to have the .ods file for Boba U4 62g (https://github.com/bluepylons/Open-Switch-Curve-Meter/blob/main/Force%20curve%20measurements/Gazzew-Boba-U4-62g.ods) but you're missing the graph. Would be nice to have the graph as well!

**Comment by bluepylons** [comment]
I ended up remeasuring the Boba U4 62g, so there's a new graph up now. 

![Gazzew Boba U4 62g](https://github.com/bluepylons/Open-Switch-Curve-Meter/blob/main/Force%20curve%20measurements/Gazzew-Boba-U4-62g-remeasured.png?raw=true)
